export const ABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "initialOracleAddress",
        type: "address",
        internalType: "address",
      },
      { name: "systemPrompt", type: "string", internalType: "string" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEDUCTIBLE_MULTIPLIER",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_ITERATIONS",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PREMIUM_PENALTY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "agentRuns",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "owner", type: "address", internalType: "address" },
      {
        name: "responsesCount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "max_iterations", type: "uint8", internalType: "uint8" },
      { name: "is_finished", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claim",
    inputs: [{ name: "message", type: "string", internalType: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositPremium",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "findClaimConclusion",
    inputs: [{ name: "input", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "forecastPremium",
    inputs: [
      { name: "message", type: "string", internalType: "string" },
      { name: "newPrompt", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getMessageHistoryContents",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "string[]", internalType: "string[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMessageHistoryRoles",
    inputs: [{ name: "agentId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "string[]", internalType: "string[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "indexCid",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "insuredAmount",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isRunFinished",
    inputs: [{ name: "runId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onOracleFunctionResponse",
    inputs: [
      { name: "runId", type: "uint256", internalType: "uint256" },
      { name: "response", type: "string", internalType: "string" },
      { name: "errorMessage", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onOracleOpenAiLlmResponse",
    inputs: [
      { name: "runId", type: "uint256", internalType: "uint256" },
      {
        name: "response",
        type: "tuple",
        internalType: "struct IOracle.OpenAiResponse",
        components: [
          { name: "id", type: "string", internalType: "string" },
          { name: "content", type: "string", internalType: "string" },
          {
            name: "functionName",
            type: "string",
            internalType: "string",
          },
          {
            name: "functionArguments",
            type: "string",
            internalType: "string",
          },
          { name: "created", type: "uint64", internalType: "uint64" },
          { name: "model", type: "string", internalType: "string" },
          {
            name: "systemFingerprint",
            type: "string",
            internalType: "string",
          },
          { name: "object", type: "string", internalType: "string" },
          {
            name: "completionTokens",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "promptTokens",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "totalTokens",
            type: "uint32",
            internalType: "uint32",
          },
        ],
      },
      { name: "errorMessage", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "oracleAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "premiumBalances",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "premiumDeposits",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "prompt",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "runAgent",
    inputs: [
      { name: "query", type: "string", internalType: "string" },
      { name: "max_iterations", type: "uint8", internalType: "uint8" },
      { name: "newPrompt", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "i", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOracleAddress",
    inputs: [
      {
        name: "newOracleAddress",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "storeInsuredAmount",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AgentRunCreated",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "runId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DeductibleLocked",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InsuredAmountSet",
    inputs: [
      {
        name: "payer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OracleAddressUpdated",
    inputs: [
      {
        name: "newOracleAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentSent",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PenaltyAdded",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PremiumDeposited",
    inputs: [
      {
        name: "payer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "day",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "month",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "year",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AlreadyDeposited",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "AlreadySetInsuredAmount",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "MissingInsuredAmount",
    inputs: [{ name: "", type: "address", internalType: "address" }],
  },
];
