import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/AuthProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import ModalProvider from "@/context/ModalProvider";
import Modal from "@/components/ui/Modal";
import WeatherDataProvider from "@/context/WeatherProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`} >
        <AuthProvider>
          <WeatherDataProvider>
            <ModalProvider>
              <Header />
              <main className="flex-grow">{children}</main>
              <Modal />
              <Toaster />
            </ModalProvider>
          </WeatherDataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
